### ISSUE TITLE
Missing bitcoin donation address

### ISSUE THREAD

**Issue by iron77** [camAtGitHub/crack-btc-bip38-password#1]
As your code and instructions (especially the 5th point) have proven themselves to be quite practical, I now find myself in an unpleasant situation, where I don't know where should I send the thank-you coins to.

**Comment by camAtGitHub** [comment]
lol - thanks very much (if your still inclined...) I have updated the readme with a btc address

**Comment by iron77** [comment]
Thanks, it was quite useful to have that code in hand in scary situation :).
